//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SyncOAdll
{
    using System;
    using System.Collections.Generic;
    
    public partial class KWAttachments
    {
        public int ProjectID { get; set; }
        public int AttachmentID { get; set; }
        public Nullable<int> AttachmentTypeID { get; set; }
        public Nullable<int> IssueID { get; set; }
        public string AttachmentTitle { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<int> CreatedByID { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public Nullable<int> ModifiedByID { get; set; }
        public Nullable<int> AttachmentFileID { get; set; }
        public string AttachmentFileName { get; set; }
        public Nullable<int> AttachmentFolderID { get; set; }
        public Nullable<int> AttachmentVersionNo { get; set; }
        public Nullable<int> LastCheckOutBy { get; set; }
        public Nullable<System.DateTime> LastCheckOutDate { get; set; }
        public string CheckOutPath { get; set; }
        public Nullable<System.DateTime> LastCheckInDate { get; set; }
        public Nullable<int> LastCheckInBy { get; set; }
        public Nullable<int> IssueTypeID { get; set; }
        public Nullable<int> AttachmentProjectID { get; set; }
        public string AttachmentDescription { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public Nullable<int> IfSavedtoProjMaster { get; set; }
        public Nullable<int> CreatedFromSiteID { get; set; }
        public Nullable<int> OfflineFileID { get; set; }
        public string LinkedIdeaID { get; set; }
        public Nullable<int> TemplateFileID { get; set; }
        public Nullable<int> IdeaProcessStatus { get; set; }
        public Nullable<int> IdeaPageCount { get; set; }
        public Nullable<System.DateTime> EnterTime { get; set; }
        public Nullable<System.DateTime> ProcessStartTime { get; set; }
        public Nullable<System.DateTime> ProcessEndTime { get; set; }
        public string IdeaErrorMessage { get; set; }
        public string HyperLinkInfo { get; set; }
        public string DisplayFileName { get; set; }
        public Nullable<int> ParentItemID { get; set; }
    }
}
