//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SyncOAdll
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GXX_DSEntities : DbContext
    {
        public GXX_DSEntities()
            : base("name=GXX_DSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Bug> Bug { get; set; }
        public virtual DbSet<CustomerFieldTrackExt> CustomerFieldTrackExt { get; set; }
        public virtual DbSet<CustomerFieldTrackExt2> CustomerFieldTrackExt2 { get; set; }
        public virtual DbSet<KWAttachments> KWAttachments { get; set; }
        public virtual DbSet<LogIn> LogIn { get; set; }
        public virtual DbSet<ProgressStatusTypes> ProgressStatusTypes { get; set; }
    }
}
